name: Comment Artifact on PR

on:
  workflow_run:
    types:
      - 'completed'
    workflows:
      - 'Check PR'

jobs:
  comment-on-pr:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.artifacts_url != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifact URL & PR Info
        env:
          GITHUB_TOKEN: ${{ github.token }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          WORKFLOW_RUN_EVENT_OBJ: ${{ toJSON(github.event.workflow_run) }}
        run: |
          PREVIOUS_JOB_ID=$(jq -r '.id' <<< "$WORKFLOW_RUN_EVENT_OBJ")
          echo "Previous Job ID: $PREVIOUS_JOB_ID"
          echo "PREVIOUS_JOB_ID=$PREVIOUS_JOB_ID" >> "$GITHUB_ENV"

          # Retrieve artifact URLs and names as an array
          ARTIFACTS=$(gh api "/repos/$OWNER/$REPO/actions/artifacts" \
            --jq ".artifacts.[] |
            select(.workflow_run.id==${PREVIOUS_JOB_ID}) |
            select(.expired==false) |
            {name: .name, url: .archive_download_url, expires: .expires_at}")

          if [ -z "$ARTIFACTS" ]; then
            echo "Error: No artifacts found for workflow run $PREVIOUS_JOB_ID"
            exit 1
          fi

          # Convert artifacts to a markdown table
          ARTIFACT_TABLE=$(echo "$ARTIFACTS" | jq -r '. | "\(.name) | [\(.name)](\(.url)) | \(.expires)"' | sed 's/ *|/ |/g')
          echo "ARTIFACT_TABLE<<EOF" >> "$GITHUB_ENV"
          echo "$ARTIFACT_TABLE" >> "$GITHUB_ENV"
          echo "EOF" >> "$GITHUB_ENV"

          PR_NUMBER=$(jq -r '.pull_requests[0].number' <<< "$WORKFLOW_RUN_EVENT_OBJ")
          if [ -z "$PR_NUMBER" ] || [ "$PR_NUMBER" == "null" ]; then
            echo "Error: No PR number found"
            exit 1
          fi
          echo "PR Number: $PR_NUMBER"
          echo "PR_NUMBER=$PR_NUMBER" >> "$GITHUB_ENV"

          HEAD_SHA=$(jq -r '.pull_requests[0].head.sha' <<< "$WORKFLOW_RUN_EVENT_OBJ")
          echo "Head sha: $HEAD_SHA"
          echo "HEAD_SHA=$HEAD_SHA" >> "$GITHUB_ENV"

      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: find-comment
        with:
          issue-number: ${{ env.PR_NUMBER }}
          comment-author: 'github-actions[bot]'

      - name: Update Comment
        env:
          JOB_PATH: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ env.PREVIOUS_JOB_ID }}'
          HEAD_SHA: ${{ env.HEAD_SHA }}
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ env.PR_NUMBER }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            ## Build Preview

            [![badge]]($JOB_PATH)

            Build Successful! You can find links to the downloadable artifacts below.

            | Artifact Name | Download Link | Expires At |
            | ------------- | ------------- | ---------- |
            ${{ env.ARTIFACT_TABLE }}
            | Commit        | ${{ env.HEAD_SHA }} | - |
            | Logs          | ${{ env.JOB_PATH }} | - |

            [badge]: https://img.shields.io/badge/Build_Success!-0d1117?style=for-the-badge&labelColor=3fb950&logo=data:image/svg%2bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNCAyNCIgd2lkdGg9IjI0IiBoZWlnaHQ9IjI0IiBmaWxsPSIjZmZmZmZmIj48cGF0aCBkPSJNMjEuMDMgNS43MmEuNzUuNzUgMCAwIDEgMCAxLjA2bC0xMS41IDExLjVhLjc0Ny43NDcgMCAwIDEtMS4wNzItLjAxMmwtNS41LTUuNzVhLjc1Ljc1IDAgMSAxIDEuMDg0LTEuMDM2bDQuOTcgNS4xOTVMMTkuOTcgNS43MmEuNzUuNzUgMCAwIDEgMS4wNiAwWiI+PC9wYXRoPjwvc3ZnPg==
