name: Check PR

on:
  pull_request:
    branches: [main]

jobs:
  lint-and-format-check:
    name: Lint & Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup Dependencies
        uses: ./.github/actions/setup-dependencies
        with:
          node-version: '20'
          platform: ubuntu-latest

      - name: Run ESLint
        run: npm run lint

  tauri-build-check:
    name: Build App
    needs: [lint-and-format-check]
    environment: pr-check
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v5
      - name: Setup Dependencies
        uses: ./.github/actions/setup-dependencies
        with:
          node-version: '20'
          platform: ${{ matrix.platform }}

      - name: Run Tauri Build Check
        run: npm run tauri:build:dev"

      - name: Upload Combined Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-build-zip
          path: src-tauri/target/release/bundle/
          compression-level: 9
