name: Lingvo Injector App Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release-build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
        # platform: [ubuntu-latest, windows-latest, macos-latest] # Uncomment for macOS support

    runs-on: ${{ matrix.platform }}

    environment: release

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install Frontend Dependencies
        run: npm ci

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            ./src-tauri/target
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-rust-

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install Dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf rpm

      # - name: Install Dependencies (macOS only)
      #   if: matrix.platform == 'macos-latest'
      #   run: |
      #     brew install webkit2gtk libappindicator librsvg

      - name: Build and Sign Tauri Application
        uses: tauri-apps/tauri-action@v0
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseDraft: true
          tagName: ${{ github.ref_name }}
          includeUpdaterJson: true
          releaseName: ${{ github.ref_name }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-build-artifacts-${{ matrix.platform }}-${{ github.ref_name }}
          path: src-tauri/target/release/bundle/*
