name: Lingvo Injector App Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release-build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest]
        # platform: [ubuntu-latest, windows-latest, macos-latest] # Uncomment for macOS support

    runs-on: ${{ matrix.platform }}

    environment: release

    steps:
      - name: Setup Dependencies
        uses: ./.github/actions/setup-dependencies
        with:
          node-version: '20'
          platform: ${{ matrix.platform }}

      - name: Build and Sign Tauri Application
        uses: tauri-apps/tauri-action@v0
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseDraft: true
          tagName: ${{ github.ref_name }}
          includeUpdaterJson: true
          releaseName: ${{ github.ref_name }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-build-artifacts-${{ matrix.platform }}-${{ github.ref_name }}
          path: src-tauri/target/release/bundle/*
